version: '3.5'
services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    build: ./docker/nginx
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - .:/var/www/${COMPOSE_PROJECT_NAME}
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      NGINX_PORT: ${NGINX_PORT},
    links:
      - front
  front:
    container_name: ${COMPOSE_PROJECT_NAME}_front
    build:
      context: ./docker/front
    volumes:
      - .:/var/www/${COMPOSE_PROJECT_NAME}
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
